name: square_switch
description: A flutter package that contains a square switch.
version: 0.0.1
author: Felipe Macedo
homepage: TODO add a git address

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
